### PR TITLE
Added ability to run Moloch on http instead of https.

### PR DESCRIPTION
**Pull request by keithjjones**
Fix for issue #1198 

Just adds a new setting to the Moloch settings in reporting.conf and uses logic appropriately.

### CODE REVIEW

**Comment by jbremer** [comment]
Does `moloch` even support non-https? Last I checked I don't think they did (by default, anyway).

**Comment by keithjjones** [comment]
Yeah, I'm running it that way right now @jbremer on an Ubuntu fresh install.

**Comment by keithjjones** [comment]
Pull request submitted for this issue.  Please test and merge if appropriate.

**Comment by SparkyNZL** [comment]
while this works in the packaged version of cuckoo I do get an error from the web console

017-02-04 12:59:19,674 [cuckoo.common.config] ERROR: Type of config parameter reporting:moloch:insecure not found! This may indicate that you've incorrectly filled out the Cuckoo configuration, please double check it.

I have double triple quad checked it. the config that is

reporting.conf
[moloch]
enabled = yes
# If you wish to run Moloch in http (insecure) versus https (secure) set
# insecure to yes
insecure = yes
#
# If the Moloch web interface is hosted on a different IP address than the
# Cuckoo Web Interface then you'll want to override the IP address here.
host = 192.168.20.50

views.py
        hostname = request.get_host()

#    url = "https://%s:8005/?%s" % (
    if settings.MOLOCH_INSECURE:
       url = "http://"
    else:
        url = "https://"

    url += "%s:8005/?%s" % ( 
        settings.MOLOCH_HOST or hostname,
        urllib.urlencode({

setting.py

MOLOCH_ENABLED = cfg.moloch.get("enabled")
MOLOCH_HOST = cfg.moloch.get("host")
MOLOCH_INSECURE = cfg.moloch.get("insecure")

**Comment by jbremer** [comment]
@SparkyNZL That's because the configuration value should be defined in `cuckoo/common/config.py`  as well :) I suppose we can merge this though, I'll do so soon'ish.

**Comment by SparkyNZL** [comment]
arr ok cool, sorted :) Sorry about the dumb questions but im only starting to get my head around the architecture :)

**Comment by keithjjones** [comment]
Sweet.

**Comment by jbremer** [comment]
Looks fine, thanks!

**Pull request merged**
