### PR TITLE
Rooter

### PR DESCRIPTION
**Pull request by doomedraven**
here we go :)

inetsim
```
wget
https://googledrive.com/host/0B6fULLT_NpxMQ1Rrb1drdW42SkE/remnux-6.0-ova
-public.ova
tar xvf remnux-6.0-ova-public.ova
qemu-img convert -O qcow2 REMnuxV6-disk1.vmdk remnux.qcow2 # or convert
to your format
# set permament ip and configure it in conf

```
tor
```
To install Tor, follow the guide option 2, not option 1,
[here](https://www.torproject.org/docs/debian.html.en)

Once Tor is installed, edit its configuration file

$ sudo nano /etc/tor/torrc
Add the following lines to the bottom:

TransListenAddress 192.168.56.1
TransPort 9040
DNSListenAddress 192.168.56.1
DNSPort 5353
Note: 192.168.56.1 is the default address for the first VirtualBox
host-only adaptor (vboxnet0). Adjust as necessary for your
virtualization setup to match Cuckoo's result server IP address.

Then restart Tor:

$ sudo service tor restart
$ sudo uupdate-rc.d tor defautls
```

### CODE REVIEW

**Comment by doomedraven** [comment]
@jakesyl which is the problem?

**Comment by doomedraven** [comment]
@jbremer i also add drop all traffic less communication between agent and result server, i can push it here if you interested, will leave a copy also here not as commit

```
def drop_enable(ipaddr, resultserver_port):
  run(settings.iptables, "-t", "nat", "-I", "PREROUTING", "--source", ipaddr,
      "-p", "tcp", "--syn", "--dport", resultserver_port, "-j", "ACCEPT")
  run(settings.iptables, "-A", "INPUT", "--destination", ipaddr, "-p", "tcp", "--dport", "8000", "-j", "ACCEPT")
  run(settings.iptables, "-A", "INPUT", "--destination", ipaddr, "-p", "tcp", "--sport", resultserver_port, "-j", "ACCEPT")
  run(settings.iptables, "-A", "OUTPUT", "--destination", ipaddr, "-p", "tcp",  "--dport", "8000", "-j", "ACCEPT")
  run(settings.iptables, "-A", "OUTPUT", "--destination", ipaddr, "-p", "tcp",  "--sport", resultserver_port, "-j", "ACCEPT")
  run(settings.iptables, "-A", "OUTPUT", "--destination", ipaddr, "-j", "LOG")
  run(settings.iptables, "-A", "OUTPUT", "--destination", ipaddr, "-j", "DROP")

def drop_disable(ipaddr, resultserver_port):
  run(settings.iptables , "-t", "nat", "-D", "PREROUTING", "--source", ipaddr,
      "-p", "tcp", "--syn", "--dport", resultserver_port, "-j", "ACCEPT")
  run(settings.iptables, "-D", "INPUT", "--destination", ipaddr, "-p", "tcp", "--dport", "8000", "-j", "ACCEPT")
  run(settings.iptables, "-D", "INPUT", "--destination", ipaddr, "-p", "tcp", "--sport", resultserver_port, "-j", "ACCEPT")
  run(settings.iptables, "-D", "OUTPUT", "--destination", ipaddr, "-p", "tcp", "--dport", "8000", "-j", "ACCEPT")
  run(settings.iptables, "-d", "OUTPUT", "--destination", ipaddr, "-p", "tcp",  "--sport", resultserver_port, "-j", "ACCEPT")
  run(settings.iptables, "-D", "OUTPUT", "--destination", ipaddr, "-j", "DROP")

```

**Comment by jbremer** [comment]
Works smoothly - thanks a lot! Merging it only for the `package` branch, though ;-)

**Comment by jbremer** [comment]
Going to close this PR as Github doesn't recognize it's been merged (or maybe it will only see that once I merge `package` with `master`), anyway, you can find it here https://github.com/cuckoosandbox/cuckoo/compare/94f8d5dc9765...d859a22ccf14. Thanks again!

**Comment by doomedraven** [comment]
drop_enable and drop_disable are not there, do you want me add that with another pr?

**Comment by jbremer** [comment]
Yeah - if you like. Although I'm not entirely sure about its use-case, is it for avoiding communication between VMs and all that?

**Comment by doomedraven** [comment]
ok will push in a moment, use-case

you don't want malware connect to any place, neither inetsim, to see how it will behave, as many malware will loop dga/urls list until one will be reached. for example one of the use case

**Comment by jbremer** [comment]
So would you want to replace the `none` route with the `drop` policy, or create a new `drop` route for that? (The `none` route is still useful for contacting e.g. a http server on the host machine).

**Comment by doomedraven** [comment]
if `none` allows that action, that `drop` route would be used to not allow anything, only cuckoo result server

**Pull request closed without merging**
