### PR TITLE
misp integration

### PR DESCRIPTION
**Pull request by doomedraven**
enjoy :)

### CODE REVIEW

**Comment by jbremer** [comment]
Thanks @doomedraven. I've modified it a bit and will also work on a reporting module for MISP soon - awaiting some feedback from the MISP guys.

**Comment by doomedraven** [comment]
@jbremer you are welcome, and thanks to accept it even with your mods :)

**Comment by doomedraven** [comment]
@jbremer you are welcome, and thanks for accept it even with your mods :)

**Pull request merged**
