### PR TITLE
Integration of cuckoo-linux prototype into cuckoo.

### PR DESCRIPTION
**Pull request by 0x71**
Hi,

As discussed, I provide the pull request without all the small changes again ;-) 

For the moment, I created the file analyzer/linux/analyzer2.py and agent/agent2.py as we should discuss the possibilities to merge both analysis approaches together. Running agent2.py into a linux guest, it will execute analyzer2.py to start the analysis (as a temporary solution).

Best regards,
Nils

### CODE REVIEW

**Comment by jbremer** [comment]
@0x71 Do you have any insight on what's different between your work and the work already present in Cuckoo, courtesy of @rep? I could totally see merging the added value of your work with what we already have as of this day, but I believe there's quite some overlap and thus it wouldn't make sense to have both the linux analyzers in our code base.

**Comment by 0x71** [comment]
Hi @jbremer and sorry for my late reply. You are absolutely right. There is some overlap between both linux analyzers. However, there are two major differences:

1) While both stap and ptrace are used to observe system calls, ptrace additionally allows system call interceptions and return value modifications, for example. This feature enables us to hide our analysis and to protect the sandbox against any detection attempts. As one can see in [analyzer/linux/lib/api/tracer.py](https://github.com/0x71/cuckoo/blob/master/analyzer/linux/lib/api/tracer.py), I implemented a small function `hide_me` for illustration purpose. That function simply modifies the return value of the ptrace syscall that is used by some malware authors to detect process monitoring or debugging. 

2) Based on your monitor (formerly cuckoomon) I implemented a live logging module to directly send the logs captured during the analysis to the result server. Thus, if the analysis machine crashed for any reason, the latest analysis data would still be available on the host. If I understood the source code correctly, the current implementation waits for the analysis to be finished before sending the logged data to the host. 

If you can still see merging my code to your project, I could implement my syscall tracer as auxiliary module (according to @rep's current implementation) as it is currently placed in linux/lib/api and directly called in analyzer.py

**Comment by doomedraven** [comment]
@0x71 i'm taking a look on this one, thanks for goodies :)

**Comment by doomedraven** [comment]
the main problem which i see here is the logging, the rest is easy portable/upgradable to extend current setup, but the monitor logging is where in stuck. @0x71 it would be more useful i think make it as aux so that won't affected by monitor/logging part, let me know if you still interested in this

**Comment by doomedraven** [comment]
i have ported it to aux module already for cuckoo v2, PR should appear soon

```
2017-04-26 08:55:39,279 [root] DEBUG: SyscallTracer started.
2017-04-26 08:55:39,289 [root] INFO: Debugger trace forks (options=7)
2017-04-26 08:55:39,281 [watchdog.observers.inotify_buffer] DEBUG: in-event <InotifyEvent: src_path=/tmp/tmpfhkF78X, wd=1, mask=IN_MODIFY, cookie=0, name=tmpfhkF78X>
2017-04-26 08:55:39,304 [root] INFO: Attach <PtraceProcess #939> to debugger
2017-04-26 08:55:39,310 [watchdog.observers.inotify_buffer] DEBUG: in-event <InotifyEvent: src_path=/tmp/tmpfhkF78X, wd=1, mask=IN_MODIFY, cookie=0, name=tmpfhkF78X>
2017-04-26 08:55:39,328 [root] ERROR: Process can no be attached! Process 939 terminated abnormally
2017-04-26 08:55:39,330 [root] INFO: Quit debugger
2017-04-26 08:55:39,360 [root] DEBUG: Started auxiliary module STRACER
2017-04-26 08:55:39,313 [watchdog.observers.inotify_buffer] DEBUG: in-event <InotifyEvent: src_path=/tmp/tmpfhkF78X, wd=1, mask=IN_MODIFY, cookie=0, name=tmpfhkF78X>
2017-04-26 08:55:39,481 [watchdog.observers.inotify_buffer] DEBUG: in-event <InotifyEvent: src_path=/tmp/tmpfhkF78X, wd=1, mask=IN_MODIFY, cookie=0, name=tmpfhkF78X>
2017-04-26 08:55:39,653 [watchdog.observers.inotify_buffer] DEBUG: in-event <InotifyEvent: src_path=/tmp/x64_ddos.elf, wd=1, mask=IN_ATTRIB, cookie=0, name=x64_ddos.elf>
2017-04-26 08:55:39,778 [watchdog.observers.inotify_buffer] DEBUG: in-event <InotifyEvent: src_path=/tmp/tmpfhkF78X, wd=1, mask=IN_MODIFY, cookie=0, name=tmpfhkF78X>
2017-04-26 08:55:39,823 [root] INFO: Modified file: /tmp/tmpfhkF78X
2017-04-26 08:55:39,820 [root] INFO: Added new process to list with pid: 1019
```

**Comment by 0x71** [comment]
@doomedraven Thank you for your support. I am still interested in this. Looking forward to your PR :)

**Comment by doomedraven** [comment]
Thanks for great work, im testing it in local and results are very nice, i also have my setup up and running here https://linux.huntingmalware.com/ but at the moment behavior works on x32 bits(systemtap), but with your support should works on all arches, once it finished i will let you know

**Comment by doomedraven** [comment]
biggest part is done, https://github.com/cuckoosandbox/cuckoo/compare/master...doomedraven:master
i work on add static, but without objdump and subprocess but instead use https://github.com/eliben/pyelftools

and few other things which i have in ToDo :)

the FS part i also will backport from darwin like this

```

    def handle_files(self, call):
        """ Remember what files our target has been working with during the analysis"""
        def makeabs(filepath):
            # Is it a relative path? Suppose it's relative to our dtrace working directory
            if not path.isfile(filepath):
                filepath = path.join(path.dirname(__file__), "..", "dtrace", filepath)
            return filepath
        if call.api in ["fopen", "freopen", "open"]:
            self.open_file(makeabs(call.args[0]))
        if call.api in ["rename"]:
            self.move_file(makeabs(call.args[0]), makeabs(call.args[1]))
        if call.api in ["copyfile"]:
            self.copy_file(makeabs(call.args[0]), makeabs(call.args[1]))
        if call.api in ["remove", "unlink"]:
            self.remove_file(makeabs(call.args[0]))
```

**Comment by doomedraven** [comment]
everything is ported and some parts even extended, thanks @0x71 for great work

**Comment by 0x71** [comment]
@doomedraven you did a great job as well! Thank you for porting and extending my PR. Are you going to create a new PR?

**Comment by doomedraven** [comment]
thanks, yes, we spoke with @jbremer how to best to do it, so yes, now I'm doing last tests in production as im deploying it and see if I have missed something. but yes new pr will appear today or tomorrow :)

**Comment by 0x71** [comment]
Great! :) Hope it will be integrated soon.

**Comment by jbremer** [comment]
Thanks again for the contribution @0x71. As the new Linux Analyzer stuff by @doomedraven & @daanfs has been merged (and released in `2.0.4`) this PR has now been superseded. Closing it as such.

**Pull request closed without merging**
