### PR TITLE
Fix memory snapshot download for vSphere 6.x

### PR DESCRIPTION
**Pull request by jgajek**
To address issues #901, #905 and #1042.

### CODE REVIEW

**Comment by jbremer** [comment]
Thanks!

**Comment by Lindi16** [comment]
Hey, ähm ;D i still have the same issue: empty mem. dumps...
btw. i guess #975 is also related here ;D

**Comment by jgajek** [comment]
@Lindi16 Please post the cuckoo log snippet and which version of ESXi you are running.

**Comment by Lindi16** [comment]
```
2016-08-22 18:04:28,821 [lib.cuckoo.core.guest] INFO: cuckoo_vm_000: analysis completed successfully
2016-08-22 18:04:29,114 [modules.machinery.vsphere] INFO: Creating snapshot cuckoo_memdump_671299 for machine CDC-CUCKOO-CLUSTER-SLAVE-WIN7-000
2016-08-22 18:04:32,196 [modules.machinery.vsphere] INFO: Downloading memory dump [CDC_ERNA_Internal_Storage] CDC-CUCKOO-CLUSTER-SLAVE-WIN7-01/CDC-CUCKOO-CLUSTER-SLAVE-WIN7-01-Snapshot33.vmem to /sandbox/cuckoo/storage/analyses/4/memory.dmp
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:838: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/security.html
  InsecureRequestWarning)
2016-08-22 18:04:32,226 [modules.machinery.vsphere] INFO: Removing snapshot cuckoo_memdump_671299 for machine CDC-CUCKOO-CLUSTER-SLAVE-WIN7-000
2016-08-22 18:04:34,461 [modules.machinery.vsphere] INFO: Powering off virtual machine CDC-CUCKOO-CLUSTER-SLAVE-WIN7-000
2016-08-22 18:04:37,488 [modules.processing.memory] ERROR: Generic error executing volatility
Traceback (most recent call last):
  File "/sandbox/cuckoo/modules/processing/memory.py", line 1028, in run
    results = VolatilityManager(self.memory_path).run()
  File "/sandbox/cuckoo/modules/processing/memory.py", line 948, in run
    vol = VolatilityAPI(self.memfile, self.osprofile)
  File "/sandbox/cuckoo/modules/processing/memory.py", line 59, in __init__
    self.init_config()
  File "/sandbox/cuckoo/modules/processing/memory.py", line 113, in init_config
    self.addr_space = utils.load_as(self.config)
  File "/usr/local/lib/python2.7/dist-packages/volatility-2.5-py2.7.egg/volatility/utils.py", line 65, in load_as
    raise error
AddrSpaceError: No suitable address space mapping found

```



virsh # version
```
Compiled against library: libvirt 1.3.4
Using library: libvirt 1.3.4
Using API: ESX 1.3.4
Running hypervisor: ESX 6.0.0
```

**Comment by jgajek** [comment]
OK, so it is downloading the .vmem file as expected.  Did you confirm that /sandbox/cuckoo/storage/analyses/4/memory.dmp is empty?

**Comment by Lindi16** [comment]
`mli@CDC-CUCKOO-CLUSTER-MASTER-01:/sandbox/cuckoo/storage/analyses/4$ ls -la | grep memory.dmp 
-rw-rw-r-- 1 mli mli     0 Aug 22 18:04 memory.dmp`

**Comment by jgajek** [comment]
You can try commenting out the "self._delete_snapshot(vm, name)" on line 185 in vsphere.py to keep the snapshot files on the ESXi server.  That should allow you to browse to the datastore on the server and confirm that the relevant .vmem file actually has non-empty content.  If it does, then something is preventing the file from being downloaded correctly via HTTPS.

**Comment by Lindi16** [comment]
@jgajek okay, thanks for the fast and excelent support :) i will try it tomorrow ;-)

**Comment by Lindi16** [comment]
okay checked 2things:
-> *.vmem files exists at the Datastore (and has a propitiate size)
-> the test machine **WIN-000 was originally ***WIN-01 and i renamed it, and so i thought maybe cuckoo has it issues withe the Data-path ***WIN-01 and the machinename ***WIN-000 but the new machine i tested this moment also doesnt work 👎 

I honestly don't know what to do/ what to try?
(and a setup with 20 guest's is to much to put in one vm^^)

**Comment by jgajek** [comment]
At this point I suspect something going wrong with the HTTPS download of the .vmem file.  There is no evidence of an exception being thrown by the requests module in the log snippet you posted, but there are some warnings that indicate you might be using an older version of Python 2.7.  Perhaps you can try upgrading the Python 2.7 package on the machine running Cuckoo if you have that option.

Also, check that the account that you are using to connect to the ESXi host from Cuckoo has permissions to access the datastore and download files for the Cuckoo guest VMs.

**Comment by Lindi16** [comment]
@jgajek so i added a few logging lines to the code:
as response i get: 401 ->
But we don't know what permission is missing on the esx:
i do have full access to the VMs, i do have acces to the dada-store / can download/move/rename/clone the files via de web-if...
so we don't know what's missing ;D

**Comment by jgajek** [comment]
Perhaps it's not liking the authentication cookie the vSphere module is sending for some reason.  You can try replacing the 'headers' parameter in the requests.get() call on line 367 with auth=("user", "pass") so that the call would look like this:

response = requests.get(url, params=params, auth=("user", "pass"), verify=False, stream=True)

Replace the "user" and "pass" with the appropriate credentials of course.  If this works, then it's a problem with the cookie, otherwise it is a true permission problem with the account you are using and we'll need to figure out the relevant permission to grant to the account.  For vSphere 5, the required permissions are documented here:

https://pubs.vmware.com/vsphere-50/index.jsp#com.vmware.wssdk.pg.doc_50/PG_ChC_Http_Access.21.3.html?path=5_0_1_18_1_3#1067262

Looks like System.View, Datastore.Browse, and Datastore.FileManagement permissions are required.

**Comment by Lindi16** [comment]
tried the auth - way -> doen't work
(btw. updated to python 2.7.10 (fiexd the ssl-waring stuff^^))

tomorrow i will try to use more permissions :)
thanks for the great effort :)

**Comment by jgajek** [comment]
The July 23, 2015 comment by @KillerInstinct may be helpful, as he ran into a permissions issue as well:

https://github.com/cuckoosandbox/cuckoo/pull/604

I'll look into adding better error handling and documentation for this.

**Pull request merged**
