### PR TITLE
Vt intelligence download

### PR DESCRIPTION
**Pull request by doomedraven**
many users have only intelligence key, not private, this will allows them download :)

### CODE REVIEW

**Comment by jbremer** [comment]
Sweet! Needs a bit more work though.
* Verify the `apikey` `type` somewhere during startup.
* Show an error if somebody attempts to download with a `public` VT key.
* Resolve syntax error (no colon after `else`).

**Comment by jbremer** [comment]
Regarding the error reporting, I'm having my guy look at that. Still has to be done though :-)

**Comment by doomedraven** [comment]
cool :)

so leave this open or close?

**Comment by jbremer** [comment]
If you could do the `apikey` `type` verification at startup (somewhere in `startup.py`) then I'll merge it :)

**Comment by doomedraven** [comment]
ok, looking where it would be correct to put the check :)

**Comment by doomedraven** [comment]
hm thinking a bit, how you want check that in startup?
we can check if `key` is different and if `type` is `private/intelligence`
but there no option like enable downloads

what do you think about this
* i'm adding option to config `download = no`
* if that option is set to `yes`
* it will do req to vt will say to try download pafish
* in response messege we will have the status code and msg which will say if we can download or not
* if we can't download, raise exception with message about incorrect key/type

**Comment by doomedraven** [comment]
@jbremer check this :)

**Comment by jbremer** [comment]
I like the idea but it needs some work. I don't think we should do the checking for every Cuckoo startup. This PR also needs some unit tests.

**Comment by doomedraven** [comment]
i can remove check on startup easily, what you would change/improve? i will do a unit test next week

**Pull request closed without merging**
