### PR TITLE
Fix Cuckoo Rooter (Internet, TOR, inetsim) #1440 #1380 #1496

### PR DESCRIPTION
**Pull request by super-a1ice**
If you do want to use the Internet then you need open port 53.

- Internet
    - ACCEPT udp 53
- InetSim
    - ACCEPT udp 53
    - FORWARD port 53
- Tor
    - ACCEPT udp 53

### CODE REVIEW

**Comment by doomedraven** [comment]
See inetsim2 pr

**Comment by jbremer** [comment]
@tatsui @doomedraven does this PR provide additional functionality on top of #1435?

**Comment by doomedraven** [comment]
@tatsui can respond about internet enable and disable, as with host only i think that useless, and there only aprt of that are fixes for inetsim :p, but lets see what tatsui mean with that funcs

**Comment by jbremer** [comment]
Thanks! Closing PR as it doesn't seem to provide additional functionality on top of #1435. Please let us know if that's not the case, though.

**Pull request closed without merging**
