### PR TITLE
udev interface-naming change comment |ens33 v eth0

### PR DESCRIPTION
**Pull request by craigdods**

### CODE REVIEW

**Comment by jbremer** [comment]
I've seen plenty of other interface names other than `ens33`, so please update the message to be a bit more generic :-)

**Comment by craigdods** [comment]
@jbremer - ens33 is the default naming scheme for debian and ubuntu. I haven't checked other distros right now but I'm relatively certain udev + kernel 4.10+ is going to give you ens33 as your first interface (aka what eth0 used to be).

**Comment by doomedraven** [comment]
Nop, the ens part is default, bit the mumber is different

**Comment by jbremer** [comment]
And also I've seen `em1`, `em2`, etc interface names. Or `enp0s3` if you're running in VirtualBox (not to suggest that running Cuckoo in vbox is a good idea, though, just that there are some variations possible).

**Comment by erhan-** [comment]
enp0s25 on arch and I had different interface names before.

**Comment by jbremer** [comment]
I've slightly updated this PR but included it nonetheless. Thanks again and sorry for the delay in merging! I'll try to synchronize it with our official documentation soon'ish.

**Pull request closed without merging**
