### PR TITLE
fix mongo16mb problem issues,

### PR DESCRIPTION
**Pull request by doomedraven**
@jbremer due to a lot of this reported problems, see isues, that is new "timeout" error, this is easy fix and solves all this stupid issues so users can stop complain again and again

you can see verified what that works here https://github.com/cuckoosandbox/cuckoo/issues/2561

Thanks for contributing! But first: did you read our community guidelines?
https://cuckoo.sh/docs/introduction/community.html

### CODE REVIEW

**Comment by KlausItem** [comment]
After change of my mongodb.py because of the 16MB limit i got this error.
Is there anything i missed ???

Cuckoo 2.0.6

analysis completed successfully
Jan 14 08:02:16 main.c:609 main(): THREAD 0x7f8d4c93a780
2019-01-14 08:02:43,877 [cuckoo.core.plugins] ERROR: Failed to run the reporting module: MongoDB
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/cuckoo/core/plugins.py", line 623, in process
current.run(self.results)
File "/usr/local/lib/python2.7/dist-packages/cuckoo/reporting/mongodb.py", line 301, in run
log.error(str(e))
NameError: global name 'log' is not defined
2019-01-14 08:02:43,888 [cuckoo.core.scheduler] INFO: Task #1416: reports generation completed
2019-01-14 08:02:43,970 [cuckoo.core.scheduler] INFO: Task #1416: analysis procedure completed

**Comment by KlausItem** [comment]
THX

but now I got this:

analysis completed successfully
Jan 14 09:43:32 main.c:609 main(): THREAD 0x7f3bf8ad3780
2019-01-14 09:44:22,177 [cuckoo.reporting.mongodb] ERROR: BSON document too large (30241893 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2019-01-14 09:44:22,179 [cuckoo.reporting.mongodb] ERROR: Largest parent key: procmemory (1 MB)
2019-01-14 09:44:22,182 [cuckoo.core.scheduler] INFO: Task #1417: reports generation completed
2019-01-14 09:44:22,330 [cuckoo.core.scheduler] INFO: Task #1417: analysis procedure completed

Anny Idea

**Comment by doomedraven** [comment]
interpret that error as warning, thats all

**Comment by KlausItem** [comment]
OK.

But i still gett the 404 Error in the Webinterface. So that basicly means that i will not be able to view the Report in the Webinterface ???

I would be verry thankful if you have a solution

**Comment by doomedraven** [comment]
idk what is wrong with your analysis, this just remove big keys in mongo, do you have enabled fix_large_docs ? if no it just print error but not really fix it

**Comment by doomedraven** [comment]
https://github.com/cuckoosandbox/cuckoo/pull/2570/files#diff-55be65c33f3f747254cfc2f11083bc7cR301

**Comment by doomedraven** [comment]
add this `fix_large_docs = yes` to reporting.conf under mongo section, cuckoo will complain about unknown option, but meh, you can ignore it, later will extend pr

**Comment by KlausItem** [comment]
I feel sorry about this.

Still doesn't work
My reporting.conf:
[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100
# MongoDB authentication (optional).
fix_large_docs = yes
username = 
password = 

mongodb.py:
      self.db.analysis.save(report)
        except InvalidDocument as e:
            parent_key, psize = self.debug_dict_size(report)[0]
            if not self.options.get("fix_large_docs", False):
                # Just log the error and problem keys
              log.info(str(e))
              log.info("Largest parent key: %s (%d MB)" % (parent_key, int(psize) / MEGABYTE))

RESULT : Error 404 and
14 11:26:11 main.c:609 main(): THREAD 0x7f41f312b780
2019-01-14 11:26:32,339 [cuckoo.reporting.mongodb] INFO: BSON document too large (25863201 bytes) - the connected server supports BSON document sizes up to 16777216 bytes.
2019-01-14 11:26:32,340 [cuckoo.reporting.mongodb] INFO: Largest parent key: behavior (1 MB)
2019-01-14 11:26:32,342 [cuckoo.core.scheduler] INFO: Task #1420: reports generation completed
2019-01-14 11:26:32,433 [cuckoo.core.scheduler] INFO: Task #1420: analysis procedure completed


Sorry for taking your time, but It wold be great if you can still help :-(

**Comment by doomedraven** [comment]
i don't see fix in here

```
[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100
fix_large_docs = yes
```

you have missed last line

**Comment by doomedraven** [comment]
i will check that when i will have some free time, i have other priorities, but you can debug it on your own, it worked just fine for other people if you check issues

**Comment by KlausItem** [comment]
Yes i did 

[mongodb]
enabled = yes
host = 127.0.0.1
port = 27017
db = cuckoo
store_memdump = yes
paginate = 100

fix_large_docs = yes
username =
password =

**Comment by KlausItem** [comment]
But yes . thank you annyway :-)

**Comment by najashark** [comment]
@KlausItem try check your /etc//mongod.conf and add `nsSize: 128` or max 2047 it will look like this

<pre><code>
# Where and how to store data.
storage:
  dbPath: /var/lib/mongodb
  journal:
    enabled: true
#  engine:
  <b>mmapv1:</b>
    <b>nsSize: 128</b>
#  wiredTiger:
</code></pre>

ref: https://docs.mongodb.com/manual/reference/configuration-options/#storage.nsSize

**Comment by KlausItem** [comment]
Hi,

thx for the reply. I only can find a mongodb.conf in witch i found this entry:

# Specify .ns file size for new databasees.
#nssize = <size>

is it that you mentioned or do i have an old mongo or something different

**Comment by najashark** [comment]
im using mongo version v3.6.9, maybe you have an old version

try uncomment it to 
```
nssize = 128
```

**Comment by KlausItem** [comment]
THX 

i put it on 2047 and it worked.

THX THX THX ;-)

Do you know how to upgrade smooth on mongo 4.0 ;-) ???

**Comment by doomedraven** [comment]
you have instuction on mongo website how to upgrade, thanks for trick @najashark

**Comment by doomedraven** [comment]
closing this as it not an issue anymore, if we can configure in config :)

**Comment by doomedraven** [comment]
btw this mmpav1 is deprecated since mongo v3, another engine doesn't support this option

**Pull request closed without merging**
