### PR TITLE
Import Yara Rules for YaraScan Recursively

### PR DESCRIPTION
**Pull request by MiquelT**
[Issue 773](https://github.com/cuckoosandbox/cuckoo/issues/773)

For import _yarascan_ rules you have to edit the file `cuckoo/data/yara/memory/index_memory.yar` and insert all yara rules there.

It's tedious to copy all YARA rules to an unique file if you have your yara rules organized by directories.

So I propose to permit to insert your YARA rules directory at  `cuckoo/data/yara/memory/` and import all YARA rules that you can find recursively at this directory.

You could modify `cuckoo/data/yara/index_memory.yar`  and set an other path where you have all your YARA rules and it will import all of them.

### CODE REVIEW

**Comment by jbremer** [comment]
The `index_*.yar` files are created automatically when Cuckoo starts up, so I'm not sure if there's any added value in this PR?

**Comment by jbremer** [comment]
Any update here or shall I close the PR?

**Comment by MiquelT** [comment]
Sorry, you can close it. Thanks!

**Comment by jbremer** [comment]
It doesn't really matter if you close it or me, but sure :-)
So I assume you found a solution to your problem - unrelated to this PR, or?

**Pull request closed without merging**
