### PR TITLE
Lets make setting up wsgi easier for people in the future shall we

### PR DESCRIPTION
**Pull request by geudrik**
Basically a word vomit of comments in wsgi.py so that scrubs (like myself) can figure out how to set up wsgi. And more importantly, not have to re-set it up every time they do a `git pull`

### CODE REVIEW

**Comment by geudrik** [comment]
Also, on an unrelated note... wth are you doing with api.py? Why is this not part of the core code?

**Comment by jbremer** [comment]
Thanks for your contribution, but let's take a deep breath and see if it's already available in the `package` branch ;-) First of all, for usage (no more standalone `api.py`) see the comments in #863 or the development/upcoming documentation on https://cuckoo.sh/docs/usage/api.html, note that it contains information on `uWSGI`+`nginx` as well, although no `apache2` or `SSL/TLS`-support has been included - I'd be happy to see SSL/TLS support in those official docs, so feel free to PR that against the documentation in the `package` branch.
As one of the many bonus points we're also working on improving the process of installation and upgrading in `package`, but that has not been finished off, as it's really a lot of work ;-)

I think that answers both your PR as well as your question? :-)

**Comment by geudrik** [comment]
@jbremer I need to keep up to speed, clearly :P I had no idea you had a package branch / were working to overhaul the backend. I'll check out `package` and start to browse/tinker. Cheers Jurriaan!

**Comment by jbremer** [comment]
No worries! Let us know if you have any additional questions and/or suggestions :-)

**Pull request closed without merging**
