### PR TITLE
Error for Task_status_type for distributed

### PR DESCRIPTION
**Pull request by prats84**
Update to fix the issue for "task_status_type" type not found

### CODE REVIEW

**Comment by jbremer** [comment]
Thanks. Is there a way to do this in a more generic, non-postgresql, way?

**Comment by prats84** [comment]
I will continue to test with SQLAlchemy to fix it for non-psql as well.

**Comment by jbremer** [comment]
I guess we'll have to make some database migrations unit tests for distributed cuckoo as well.. :-)

**Comment by jbremer** [comment]
For what it's worth, PostgreSQL is the only database having a separate type for `enum`'s, hence some magic handling is required here.

**Comment by prats84** [comment]
Thanks. Testing underway for some more psql and mongodb for distributed.

**Comment by jbremer** [comment]
@prats84 any update on this PR by any chance? :)

**Comment by jbremer** [comment]
Can't merge PR as-is and I haven't heard of anyone else (including myself) that ran into the same issue. Closing PR. Please reopen if you have a new PR or feedback :-)

**Pull request closed without merging**
