### PR TITLE
kdbg support to speed up memory dump processing

### PR DESCRIPTION
**Pull request by doomedraven**
processing one analysis on my machine with and without kdbg
with

real    2m24.136s
user    2m13.588s
sys     0m9.280s

without

real    2m51.553s
user    2m42.492s
sys     0m8.580s

### CODE REVIEW

**Comment by doomedraven** [comment]
@jbremer what about this one? :)

**Comment by doomedraven** [comment]
@jbremer any possibility to get this merged?

**Comment by jbremer** [comment]
The idea is good, but the implementation requires some improvements. Preferably we find a more generic way to perform this logic.

**Comment by doomedraven** [comment]
not required in vol3, closing

**Pull request closed without merging**
