### PR TITLE
Misp

### PR DESCRIPTION
**Pull request by doomedraven**
integration of cuckoo iocs upload to misp

### CODE REVIEW

**Comment by doomedraven** [comment]
wait a moment for some reason it stops draw data in webgui, checking

**Comment by doomedraven** [comment]
hm was something on my side, everything works without additional changes requiered

**Comment by jbremer** [comment]
Definitely some good things in here, but two things;

* No `threading` or `multiprocessing` in the processing and reporting modules.
* It's not perfect, but submitting data back to `MISP` should be the job of a `reporting` module. Something that I've just added to the `package` branch. Yes, you'll have two `MISP` plugins for which you'll have to insert credentials (one for `processing` and one for `reporting`) but from a design perspective I think it's the most reasonable.

If you'd be interested to port the IOC gathering to the MISP reporting module, do let me know. Otherwise I'll gradually be taking things from it and putting them in there :-)

**Comment by doomedraven** [comment]
i will do it, hope guys from misp will add multiioc update to pymisp as it easy to do, but for sure will  create reporting module

**Comment by jbremer** [comment]
Yep :-) I needed it these days, so I took the liberty to take your idea and push it forward, see also https://github.com/MISP/PyMISP/pull/26.

**Comment by doomedraven** [comment]
oh awesome :D
tnx for the point

**Comment by doomedraven** [comment]
@jbremer check code now, let me know if some changes required

**Comment by doomedraven** [comment]
@jbremer btw check this one

**Comment by jbremer** [comment]
Thanks again @doomedraven! I've manually merged your changes into our existing code (in `package`) and backported it to `master` as well. See also the commits mentioned in this thread. CC @adulau

**Comment by ronbarrey** [comment]
I have been working on a MISP reporting module for Cuckoo that will further extend what you have created. I was wondering if you are interested in collaborating on the MISP-Cuckoo reporting to build it out further? Hit me up on the Cuckoo IRC.

**Comment by doomedraven** [comment]
What you missing in current one? Once all iocs type will suport bulk upload they will be integrated here too :) (not checked right now if that already done)

**Comment by ronbarrey** [comment]
Take a look at what I have built https://github.com/ronbarrey/cuckoo/blob/master/modules/reporting/misper.py. I added a checkbox in the web submission UI under advanced options for MISPER and also added MISPER to the process.py arg parser to run from command line.

**Comment by ronbarrey** [comment]
I did not mean to commit my code to replace yours. I took it down and deleted the pull request. I will integrate some of my code into yours for you to review.

**Pull request closed without merging**
