### PR TITLE
Fix display issues after reprocess

### PR DESCRIPTION
**Pull request by sebdg**
There is an update issue on the recent list, data is not correct after reprocessing.
The data is sorted by insertion id and not report id, this is then amplified with a grouping loop lower.
The score is not updated for example.

### CODE REVIEW

**Comment by sebdg** [comment]
fixes issue #1959

**Comment by sebdg** [comment]
There is a similar issue in the Behavior tab, the calls displayed are not from the latest report.
Same goes for searching and filtering view of that tab.

**Comment by jbremer** [comment]
I've manually merged this, thanks! Will close issue once it's been shipped in an official release.
Note that I've skipped the `remove extra line breaks` commit as I consider the current syntax as just fine.

**Comment by jbremer** [comment]
This has been resolved in our `2.0.5` release which we put out just now. Please upgrade and try again! Closing issue, but feel free to reopen if the issue(s) persist for you. Thanks!
Please find also our blogpost https://cuckoosandbox.org/blog/205-office-dde

**Pull request closed without merging**
