### PR TITLE
session leak fixes

### PR DESCRIPTION
**Pull request by ianepanda**

### CODE REVIEW

**Comment by jbremer** [comment]
Hi @ianepanda, are you sure about this PR? The `finally` keyword contains code that is supposed to be run *at all times*, which means both when the `try`/`catch` succeeds but also when it fails, hence this would duplicate the `session.close()` logic.

**Comment by ianepanda** [comment]
Hi, @jbremer! 
imho, if `machines.filter_by(locked=False).first()` returns `None` (all filtred machnes are `locked`) then `try/except/finnaly` will not executed.

**Comment by jbremer** [comment]
Oh, sorry, I incorrectly saw one indentation too much. That sounds correct, yes, thanks for the explanation and find. I'll try to do some tests and merge this PR right after :-)

**Comment by SparkyNZL** [comment]
This makes sense with the issue i was having #811 great spotting :)

**Comment by jbremer** [comment]
Thanks again @ianepanda :)

**Pull request merged**
