### PR TITLE
Enable ActiveX controls for Office docs

### PR DESCRIPTION
**Pull request by ronbarrey**
The change will enable ActiveX controls by default when analyzing samples.

### CODE REVIEW

**Comment by jbremer** [comment]
Looks good, thanks @ronbarrey! Do you have any samples that benefit from this change that I could use for testing? :-)

**Comment by ronbarrey** [comment]
I created a sample Word document you can use for testing. I uploaded it to VirusTotal, 1cc1dac48af793764c4a081c91fc5228.

**Comment by ronbarrey** [comment]
Malware can use ActiveX controls to execute macros, for instance using InkPicture to execute VBA code without calling Document_Open or Auto_Open. By enabling ActiverX by default, the control will execute during analysis.

**Comment by jbremer** [comment]
Works well, thanks! This has been included in our `2.0.4a3` release :-) Closing PR.

**Pull request closed without merging**
