### PR TITLE
Rooter with drop option

### PR DESCRIPTION
**Pull request by doomedraven**

### CODE REVIEW

**Comment by doomedraven** [comment]
@jbremer it wasnt possible to add this to previous pr

**Comment by jbremer** [comment]
Awesome - thanks. I think merging this would be a bit ugly for the Git history, so I'll just take your changes and credit you - I'm sure you don't mind. Thanks!

**Comment by doomedraven** [comment]
i don't care, i just want this functionality inside :)

**Comment by jbremer** [comment]
There you go sir https://github.com/cuckoosandbox/cuckoo/commit/ee54e01df57a67a95eafad70a742160b7d49f3a5, thanks again!

**Comment by doomedraven** [comment]
thanks for accept it :)

**Pull request closed without merging**
