### PR TITLE
Fix #564 and #511 change utils/web.py to a shortcut of runserver of web in Django

### LINKED ISSUE #564: Proposal: remove utils/web.py web and that it run Django web with development server
That utils/web.py not run other web interface and that run Django development server, for only develop a web user interface. Merge two webs in one.

### PR DESCRIPTION
**Pull request by jhg**
This fix #564 and when HTML reports will be deleted jinja2 can be remove from requirements.txt

### CODE REVIEW

**Comment by jhg** [comment]
Now this pull also fix #511

**Comment by jhg** [comment]
This need #578

**Comment by jbremer** [comment]
Replacing the `web.py` by calling into the Django web interface doesn't sound like a very good idea to me. When people run `web.py` they expect to see the `web.py` interface and not our new Django web interface. To me it'd be better just to remove the `web.py` altogether and at the very most leave a script that just prints an error and exits.
Thoughts @jekil @botherder?

**Comment by jhg** [comment]
When decide that do with web.py I can delete it or show a error when run web.py script.

**Comment by jhg** [comment]
@jbremer delete it or show a error when run?

**Comment by botherder** [comment]
We kind of just nuked utils/web.py. I don't think it is necessary to had this kind of trampoline, as long as the changes are appropriately reflected in the documentation.

**Comment by jbremer** [comment]
We're revamping the standalone HTML/PDF report in #863 - part of that being getting rid of these files. So closing this issue for that reason.

**Pull request closed without merging**
