### PR TITLE
Minor documentation changes

### PR DESCRIPTION
**Pull request by sebdg**
Include a sample for launching an analysis with route option
Modify linux guest operating system machine names to avoid confusion with debian

### CODE REVIEW

**Comment by jbremer** [comment]
@daanfs @doomedraven please verify :)

**Comment by doomedraven** [comment]
`docs/book/installation/guest/linux.rst` looks ok, make sense to change from debian to ubuntu as it suppoused to run ubuntu 17.04 for systemtap

another works fine too :)

**Comment by sebdg** [comment]
Also I do find the indications about networking being wrong, these steps should not be done on virtualbox for ex

**Comment by daanfs** [comment]
changes in `linux.rst` make sense to me.

**Comment by jbremer** [comment]
Thanks! Manually merged :-)

**Pull request closed without merging**
