### PR TITLE
Make rooter insert rules instead of adding them

### PR DESCRIPTION
**Pull request by seanthegeek**
By default, libvirt applies the following iptables rules to host-only
bridges on startup:

```
-P FORWARD DROP
-A FORWARD -i virbr0 -o virbr0 -j ACCEPT
-A FORWARD -o virbr0 -j REJECT --reject-with icmp-port-unreachable
-A FORWARD -i virbr0 -j REJECT --reject-with icmp-port-unreachable
```

Rooter must use the insert (-I) action rather than append (-A) so that the
new rules have a higher priority than existing ones. Otherwise,
forwarding and other commands will not work.

This is the root cause and fix for the routing problem I was having in
issue #1280.

### CODE REVIEW

**Comment by jbremer** [comment]
Good stuff, thanks again! Manually merged it and will be part of the next alpha or stable release.

**Comment by jbremer** [comment]
On second thoughts, no, this PR completely breaks our per-analysis network routing. Most of the rules are very dependant on the exact order in which they are. By using `-I` rather than `-A` you'll effectively reverse that order. In order to properly perform this PR, which is something we can work towards, we'll have to modify it a little bit.
Using rule numbers, i.e., `-I <table> <num>`, doesn't seem to be a good way - provided that other Cuckoo analyses and/or tools may be altering the `iptables` rules as well.
Most likely that leaves us with reversing the insert operations for our `iptables` entries. Naturally this should be tested well, but I'll help there.. ;-)

**Comment by seanthegeek** [comment]
@jbremer At analysis time the iptables forwarding commands are only for that VM's IP address, so there shouldn't be race conditions or broken routing wwith this PR as-is.

**Comment by seanthegeek** [comment]
Closing, as this is cor longer needed as of 2.0.3a4. VPN works. However, there are still some issues with inetsim when ran on the local system. I'll create a speperate issue for that.

**Comment by doomedraven** [comment]
yep as i told i totally not recommend run it in the same host to avoid leaks as we spoke in PM :)

**Pull request closed without merging**
