### PR TITLE
Elasticsearch report module

### PR DESCRIPTION
**Pull request by fedelemantuano**
Elasticsearch report module as discussed in issue #590 with @jbremer.

### CODE REVIEW

**Comment by jbremer** [comment]
Thanks for the initial PR @fedelemantuano. I see various improvements to be done here, though.
The `get_options` function is not used and thus can be removed completely.
The `walk_dict` is *fixing* some issues which should be fixed elsewhere. If there are problems with unicode strings then these most likely also pose a problem in the `jsondump` module, etc. It would be much preferred, by me anyway, to get rid of the `walk_dict` logic and fix the problems at the root cause.
Then, as @KillerInstinct pointed out to me a small while ago, doing `copy.deepcopy` on the results is pretty expensive. Imagine having 200mb of data in there ;)
Finally the modifications on the results itself. Like the `walk_dict` stuff I think all of these changes should be done elsewhere, i.e., probably in the `processing` stage, if at all. What's the reason behind the `datetime.strptime` thing? How does ElasticSearch translate this when importing it?

I hope not to sound too harsh or anything - just trying to get the most out of this PR! :)

**Comment by KillerInstinct** [comment]
@jbremer the datetime.strptime is used to brad a date format so that the data is stored in an index based on the started_on date. This allows ES to create index based on date which makes searching much faster, and scaleable with large datasets.

**Comment by fedelemantuano** [comment]
Hi @jbremer. Yes we can remove get_options because I don't use this function here.
I know that `copy.deepcopy` can be a problem, but in ELK module I have to change results without impact others report modules.

I do some modifications to results:
1) **virustotal**: I changed the result for solve this issue https://www.elastic.co/guide/en/elasticsearch/guide/current/complex-core-fields.html#object-arrays.
So we can search for key. For instance: `virustotal.scans.antivirus`.

2) `datetime.strptime`: in ELK is a datetime, so it's possibile search for date and not string (for instance range query). Sorting in ELK is very expensive, but if you use datetime field you can use _doc_value_ that don't use java heap (https://www.elastic.co/guide/en/elasticsearch/guide/current/doc-values.html, https://www.elastic.co/guide/en/elasticsearch/guide/current/preload-fielddata.html).

3) I added tags in results, for use filters in ELK (more performance). For instance: all analysis with network analysis, etc.

Don't worry not to sound too harsh ;)

**Comment by jbremer** [comment]
@KillerInstinct could you please provide me with an answer to the following question: would it be beneficial to use `datetime` objects in the `mongodb` backend as well?
If so I'd suggest that we switch to the usage of `datetime` objects instead of strings everywhere. In reporthtml/jsondump it's trivial to switch and that way no reporting module will have to change the results dictionary.

Other than that I like your VirusTotal & Tags additions - like the other stuff I'm oke moving that higher up (i.e., in a processing module) so that it in theory it can also be used by other reporting modules, but more specifically `mongodb` gets the same information for free.

**Comment by fedelemantuano** [comment]
Hi @jbremer I have done PR #534 to perform a query date in mongodb with pymongo.

**Comment by jbremer** [comment]
Excellent, yes. We should probably still go down the way of doing this through a processing module, though :) Probably adjust the `analysisinfo` one.

**Comment by KillerInstinct** [comment]
@jbremer : Sure it would be beneficial for searching as already observed. I'm no expert at Mongo, but I assume if we ever got around to tuning/indexing/sharding we could do that based on datetime.

**Comment by jbremer** [comment]
That's what I thought. Please allow me a bit of time (due to travelling etc up to a week or two) to properly reflect these changes. After that we update the elasticsearch module to reflect those changes and we're good to go. Deal? If somebody has the time to do this for me that's also appreciated of course!

**Comment by jbremer** [comment]
Sorry for the delay - a lot is happening. I'll be moving forward on this issue soon.

**Comment by fedelemantuano** [comment]
Hi @jbremer. I can help you, but I need to see the new process modules or I need know what do you want to change.

**Comment by jbremer** [comment]
@fedelemantuano We want to have less date strings and more `datetime` objects. But this also involves modifying some `processing` modules and the other `reporting` modules. So needs a bit of testing etc.
That, including moving the `VirusTotal` magic to the `VirusTotal` module, will allow the `ElasticSearch` module to do pretty much nothing but the `self.es.index()` part :-)

**Comment by jbremer** [comment]
Oh, and now I take another look at it, we also have to resolve this issue: https://github.com/cuckoobox/cuckoo/pull/606/files#diff-3cd940e5814382686513f88a7a4c5894R126 ;-)
One thing at a time!

**Comment by KillerInstinct** [comment]
For what its worth, the bson calls should be serializable if you index the processed results. This would have to be redone to your behavior processing, but feel free to use as a guideline:

https://github.com/KillerInstinct/cuckoo-modified/blob/patch-61/modules/reporting/elasticsearchdb.py#L63

**Comment by jbremer** [comment]
That looks exactly the same as what's happening in the MongoDB reporting module, but yeah, thanks ;)

**Comment by botherder** [comment]
Updates on this PR?

**Comment by fedelemantuano** [comment]
Sorry I'm waiting @jbremer

**Comment by jbremer** [comment]
I've reimplemented parts of this PR in a relatively simplistic way, see also https://github.com/cuckoosandbox/cuckoo/blob/master/modules/reporting/elasticsearch.py.
The timestamp stuff has not been ported over yet - as discussed earlier I'd preferably move those changes (from string representations to `datetime.datetime` objects) to the Cuckoo core, so they apply to all processing, signature, and reporting modules, rather than having specific behavior here and there.

Other than that I have yet to read up on ElasticSearch's `tags` functionality and, although I can imagine their purpose, it would help if people could share examples where tags come in handy in practice.

**Comment by fedelemantuano** [comment]
Hi @jbremer. The purpose of tags is use filter query in Elasticsearch. Example: Give me all analysis with tag Zeus. Maybe it's better don't fill tags array in this specific module, but to give to users the possibility to tag the specific task in signature module, when the analysis is terminated.

I see the new module, in https://github.com/cuckoosandbox/cuckoo/blob/master/modules/reporting/elasticsearch.py#L51
you create a new index for every task. Are you sure do you want it?
For me it's better, to manage ELK index with timestamp (purge, close index, etc.) using [curator](https://github.com/elastic/curator).

**Comment by jekil** [comment]
I am also unsure about having an index for each task, imho indexes are meant to be used in a different way. See http://elasticsearch-users.115913.n3.nabble.com/How-many-indexes-is-too-many-indexes-td4064599.html

**Comment by jbremer** [comment]
I was thinking the same as @jekil, but not sure what the *correct* approach should be - it's not definitive yet either. From what I understood @fedelemantuano's indexes were based on the day of the year, so if you analyze 1000 analyses on a particular day, all of those go in one index, right?
Surely there must be a best way to do this properly - anyone?

**Comment by fedelemantuano** [comment]
In Elasticsearch index is only a logical namespace that point to one or more phisical shards. A shard is a low-level worker unit that holds all the data. So in big installation is possible to settings more shards for a single index, but 1000 analyses is very small number.
Elasticsearch suggest to use timestamp index to manage the cluster and to use Kibana GUI.
I thinking to purge old analysis, close indexes, backup, etc.

**Comment by jbremer** [comment]
Yep. But then one index a day doesn't make sense per se either. Keep in mind that generally speaking there are two use cases for Cuckoo; CERT mode (<100 analyses a day) and mass mode (50k+ analyses a day).
Perhaps we should have a sort of rate limiting approach that applies to both situations. That is, switch to a new index when either we enter a new week (so at the very least every 7 days), or when we hit, say, 100k analyses. But then for the last part some sort of state should be kept.. meh.
And this limit also depends on whether a user index just the behavioral *summary* or whether a user also indexes all the behavioral calls; the difference between those two is on a scale of 10000x (think 100mb of behavioral calls vs a 10kb behavioral summary).

**Comment by KillerInstinct** [comment]
@jbremer In talks with the people that wrote most of the code for the fork, they also suggested it would be best to index on both Task ID and date. Indexes really depend on what your needs are. For example if you want to speed up the searching, you'd index the behavior summary keys, VT results, hashes, etc.

I know Metcalf indexed mongo for suricata stuff so that he could better search on Suricata alert definitions because the default mongo search was slow. So -- it's really all based on need and what you guys think is best for performance.

**Comment by fedelemantuano** [comment]
I suggest time based indexes (for day, for months, etc.) because is more efficient the search and the maintenance. 

ELK doesn't have problem to manage 10, 100, 1000, etc. documents. If you are a CERT your index will have a shard or if you are Malwr will have 50 shards.
You can think to do this setting a parameter in report conf. Example `prefix = cuckoo-, timebase = "%Y.%m.%d"`

It's possible to have only one logic index with the use of `alias`.

Some ELK link:
https://www.elastic.co/guide/en/elasticsearch/guide/current/time-based.html
https://www.elastic.co/guide/en/elasticsearch/guide/current/multiple-indices.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-aliases.html

**Comment by jbremer** [comment]
Sounds good to me. Let's predefine a couple of values though (i.e., `day` maps to `%Y.%m.%d` and then `week` and `month`) so users won't shoot themselves in the foot. And then default to the `month` option?
Anything else before we finish off on ES integration?

**Comment by botherder** [comment]
"or if you are Malwr will have 50 shards".
Ha, right, @jekil?

**Comment by jekil** [comment]
@botherder I see shards, shards everywhere.

**Comment by botherder** [comment]
Can we close this pull request?

**Comment by fedelemantuano** [comment]
For me yes because @jbremer has reimplemented module: https://github.com/cuckoosandbox/cuckoo/blob/master/modules/reporting/elasticsearch.py

**Pull request closed without merging**
